name: geoapps

channels:
  - conda-forge
dependencies:
  - python>=3.7
  - dask
  - discretize
  - empymod
  - fiona
  - fsspec
  - gdal
  - h5py
  - ipyfilechooser
  - ipykernel
  - ipywidgets
  - matplotlib
  - numpy
  - plotly
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - xarray
  - zarr
  - git
  - pip
  - pip:
    - git+https://github.com/MiraGeoscience/simpeg.git@feature/tiled-simulations
    - geoh5py==0.1.2
